package discordbot

// Gateway event constants
// Reference: https://discordapp.com/developers/docs/topics/gateway#commands-and-events-gateway-events
const (
	EventHello                    = "HELLO"
	EventReady                    = "READY"
	EventResumed                  = "RESUMED"
	EventInvalidSession           = "INVALID_SESSION"
	EventChannelCreate            = "CHANNEL_CREATE"
	EventChannelUpdate            = "CHANNEL_UPDATE"
	EventChannelDelete            = "CHANNEL_DELETE"
	EventChannelPinsUpdate        = "CHANNEL_PINS_UPDATE"
	EventGuildCreate              = "GUILD_CREATE"
	EventGuildUpdate              = "GUILD_UPDATE"
	EventGuildDelete              = "GUILD_DELETE"
	EventGuildBanAdd              = "GUILD_BAN_ADD"
	EventGuildBanRemove           = "GUILD_BAN_REMOVE"
	EventGuildEmojisUpdate        = "GUILD_EMOJIS_UPDATE"
	EventGuildIntegrationsUpdate  = "GUILD_INTEGRATIONS_UPDATE"
	EventGuildMemberAdd           = "GUILD_MEMBER_ADD"
	EventGuildMemberRemove        = "GUILD_MEMBER_REMOVE"
	EventGuildMemberUpdate        = "GUILD_MEMBER_UPDATE"
	EventGuildMembersChunk        = "GUILD_MEMBERS_CHUNK"
	EventGuildRoleCreate          = "GUILD_ROLE_CREATE"
	EventGuildRoleUpdate          = "GUILD_ROLE_UPDATE"
	EventGuildRoleDelete          = "GUILD_ROLE_DELETE"
	EventMessageCreate            = "MESSAGE_CREATE"
	EventMessageUpdate            = "MESSAGE_UPDATE"
	EventMessageDelete            = "MESSAGE_DELETE"
	EventMessageDeleteBulk        = "MESSAGE_DELETE_BULK"
	EventMessageReactionAdd       = "MESSAGE_REACTION_ADD"
	EventMessageReactionRemove    = "MESSAGE_REACTION_REMOVE"
	EventMessageReactionRemoveAll = "MESSAGE_REACTION_REMOVE_ALL"
	EventPresenceUpdate           = "PRESENCE_UPDATE"
	EventTypingStart              = "TYPING_START"
	EventUserUpdate               = "USER_UPDATE"
	EventVoiceStateUpdate         = "VOICE_STATE_UPDATE"
	EventVoiceServerUpdate        = "VOICE_SERVER_UPDATE"
	EventWebhooksUpdate           = "WEBHOOKS_UPDATE"
)
